# Generated by Django 5.0.14 on 2026-07-24 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CleanGoMailConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_expediteur', models.CharField(default='CleanGo', max_length=120)),
                ('email_expediteur', models.EmailField(max_length=150)),
                ('serveur_smtp', models.CharField(default='smtp.gmail.com', max_length=150)),
                ('port_smtp', models.PositiveIntegerField(default=465)),
                ('utilisateur_smtp', models.CharField(max_length=150)),
                ('mot_de_passe_chiffre', models.TextField(blank=True)),
                ('utiliser_tls', models.BooleanField(default=False)),
                ('utiliser_ssl', models.BooleanField(default=True)),
                ('actif', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cleango_configuration_mail',
            },
        ),
    ]
