# Generated by Django 5.0.14 on 2026-07-24 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprises', '0007_entreprise_date_debut_abonnement_and_more'),
        ('platform_admin', '0002_cleangomailconfiguration'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionEmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=120, unique=True)),
                ('type_notification', models.CharField(choices=[('expiration', 'Rappel d’expiration'), ('paiement', 'Confirmation de paiement')], max_length=12)),
                ('destinataires', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_abonnement', to='entreprises.entreprise')),
            ],
            options={
                'db_table': 'cleango_subscription_email_logs',
                'ordering': ['-sent_at'],
            },
        ),
    ]
