# Generated by Django 5.0.14 on 2026-07-21 14:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0003_user_collaborator_details'),
        ('entreprises', '0004_entreprise_image_uploads'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poste', models.CharField(max_length=100)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('date_embauche', models.DateField()),
                ('numero_piece_identite', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_cnps', models.CharField(blank=True, max_length=50, null=True)),
                ('salaire_brut', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('categorie_permis', models.CharField(blank=True, max_length=30, null=True)),
                ('numero_permis', models.CharField(blank=True, max_length=50, null=True)),
                ('expiration_permis', models.DateField(blank=True, null=True)),
                ('banque', models.CharField(blank=True, max_length=100, null=True)),
                ('iban', models.CharField(blank=True, max_length=50, null=True)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('mission', 'En mission'), ('conge', 'En congé'), ('suspendu', 'Suspendu'), ('inactif', 'Inactif')], default='actif', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiches_employes_creees', to='authentication.user')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employes', to='entreprises.entreprise')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiches_employes_modifiees', to='authentication.user')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fiche_employe', to='authentication.user')),
            ],
            options={
                'db_table': 'employe',
                'ordering': ['user__nom'],
            },
        ),
        migrations.AddConstraint(
            model_name='employe',
            constraint=models.UniqueConstraint(fields=('entreprise', 'numero_cnps'), name='uq_cnps_par_entreprise'),
        ),
    ]
