# Generated by Django 5.0.14 on 2026-07-21 17:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0003_user_collaborator_details'),
        ('entreprises', '0005_entreprise_taux_commission_laveur'),
    ]

    operations = [
        migrations.CreateModel(
            name='MouvementCaisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mouvement', models.CharField(choices=[('entree', 'Entrée'), ('sortie', 'Sortie')], max_length=10)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('motif', models.CharField(max_length=180)),
                ('reference', models.CharField(blank=True, max_length=50, null=True)),
                ('mode_reglement', models.CharField(choices=[('especes', 'Espèces'), ('wave', 'Wave'), ('orange', 'Orange Money'), ('mtn', 'MTN Mobile Money'), ('moov', 'Moov Money'), ('carte', 'Carte bancaire'), ('virement', 'Virement'), ('autre', 'Autre')], default='especes', max_length=20)),
                ('date_mouvement', models.DateTimeField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_caisse_crees', to='authentication.user')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements_caisse', to='entreprises.entreprise')),
            ],
            options={
                'db_table': 'mouvement_caisse',
                'ordering': ['-date_mouvement', '-pk'],
            },
        ),
    ]
