# Generated by Django 5.0.14 on 2026-07-21 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0001_initial'),
        ('passage', '0005_recalculate_commission_twenty_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='mouvementcaisse',
            name='passage',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mouvement_caisse', to='passage.passage'),
        ),
        migrations.AlterField(
            model_name='mouvementcaisse',
            name='mode_reglement',
            field=models.CharField(choices=[('especes', 'Espèces'), ('wave', 'Wave'), ('orange', 'Orange Money'), ('mtn', 'MTN Mobile Money'), ('moov', 'Moov Money'), ('carte', 'Carte bancaire'), ('virement', 'Virement'), ('forfait', 'Forfait'), ('autre', 'Autre')], default='especes', max_length=20),
        ),
    ]
