# Generated by Django 5.0.14 on 2026-07-21 18:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0003_import_passage_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='mouvementcaisse',
            name='statut_paiement',
            field=models.CharField(blank=True, choices=[('paye', 'Payé'), ('partiel', 'Partiel'), ('non_paye', 'Non payé'), ('annule', 'Annulé')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='mouvementcaisse',
            name='montant',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
