# Generated by Django 5.0.14 on 2026-07-21 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0003_user_collaborator_details'),
        ('client', '0001_initial'),
        ('entreprises', '0005_entreprise_taux_commission_laveur'),
        ('passage', '0005_recalculate_commission_twenty_percent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30)),
                ('objet', models.CharField(max_length=180)),
                ('date_emission', models.DateField()),
                ('date_echeance', models.DateField(blank=True, null=True)),
                ('montant_ht', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('remise', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('taxe', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('montant_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('montant_paye', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('statut', models.CharField(choices=[('non_paye', 'Non payée'), ('partiel', 'Partiellement payée'), ('paye', 'Payée'), ('annule', 'Annulée')], default='non_paye', max_length=12)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factures', to='client.client')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures_creees', to='authentication.user')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='entreprises.entreprise')),
                ('passage', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facture', to='passage.passage')),
            ],
            options={
                'db_table': 'facture',
                'ordering': ['-date_emission', '-pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='facture',
            constraint=models.UniqueConstraint(fields=('entreprise', 'numero'), name='uq_numero_facture_entreprise'),
        ),
    ]
