# Generated by Django 5.0.14 on 2026-07-18 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0003_user_collaborator_details'),
        ('client', '0001_initial'),
        ('entreprises', '0004_entreprise_image_uploads'),
        ('type_lavage', '0001_initial'),
        ('vehicule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_heure_debut', models.DateTimeField()),
                ('date_heure_fin', models.DateTimeField(blank=True, null=True)),
                ('date_annulation', models.DateTimeField(blank=True, null=True)),
                ('montant_paye', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mode_reglement', models.CharField(choices=[('especes', 'Espèces'), ('wave', 'Wave'), ('orange', 'Orange Money'), ('mtn', 'MTN Mobile Money'), ('moov', 'Moov Money'), ('carte', 'Carte bancaire'), ('autre', 'Autre')], max_length=15)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('annule', 'Annulé')], max_length=10)),
                ('motif_annulation', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('forfait_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('piste_id', models.PositiveBigIntegerField()),
                ('commission_employe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant_partiel_verse', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('montant_restant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('net_station', models.DecimalField(decimal_places=2, max_digits=10)),
                ('statut_reglement', models.CharField(choices=[('non_paye', 'Non payé'), ('partiel', 'Partiel'), ('paye', 'Payé')], max_length=20)),
                ('annulateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passages_annules', to='authentication.user')),
                ('caissier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='passages_encaisses', to='authentication.user')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='passages', to='client.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passages_crees', to='authentication.user')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passages_supprimes', to='authentication.user')),
                ('employe_realisateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='passages_realises', to='authentication.user')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passages', to='entreprises.entreprise')),
                ('type_lavage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='passages', to='type_lavage.typelavage')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passages_modifies', to='authentication.user')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='passages', to='authentication.user')),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='passages', to='vehicule.vehicule')),
            ],
            options={
                'db_table': 'passage',
                'ordering': ['-date_heure_debut'],
            },
        ),
    ]
