# Generated by Django 5.0.14 on 2026-07-19 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passage',
            name='mode_reglement',
            field=models.CharField(choices=[('especes', 'Espèces'), ('wave', 'Wave'), ('orange', 'Orange Money'), ('mtn', 'MTN Mobile Money'), ('moov', 'Moov Money'), ('carte', 'Carte bancaire'), ('forfait', 'Forfait'), ('autre', 'Autre')], max_length=15),
        ),
    ]
