# Generated by Django 5.0.14 on 2026-07-21 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passage', '0002_alter_passage_mode_reglement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passage',
            name='piste_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
