# Generated by Django 5.0.14 on 2026-07-21 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passage', '0003_alter_passage_piste_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passage',
            name='forfait_id',
        ),
    ]
