# Generated by Django 5.0.14 on 2026-07-24 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passage', '0005_recalculate_commission_twenty_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passage',
            name='mode_reglement',
            field=models.CharField(choices=[('especes', 'Espèces'), ('wave', 'Wave'), ('orange', 'Orange Money'), ('mtn', 'MTN Mobile Money'), ('moov', 'Moov Money'), ('carte', 'Carte bancaire')], max_length=15),
        ),
    ]
