# Generated by Django 5.0.14 on 2026-07-18 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0003_user_collaborator_details'),
        ('entreprises', '0004_entreprise_image_uploads'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeLavage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duree_estimee_min', models.IntegerField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='types_lavage_crees', to='authentication.user')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='types_lavage_supprimes', to='authentication.user')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types_lavage', to='entreprises.entreprise')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='types_lavage_modifies', to='authentication.user')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='types_lavage', to='authentication.user')),
            ],
            options={
                'db_table': 'type_lavage',
                'ordering': ['libelle'],
            },
        ),
    ]
