# Generated by Django 6.0.7 on 2026-07-16 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=30)),
                ('nom', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('prix_mensuel', models.DecimalField(decimal_places=2, max_digits=10)),
                ('devise', models.CharField(max_length=3)),
                ('max_centres', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_utilisateurs', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('quota_sms_mensuel', models.PositiveIntegerField(blank=True, null=True)),
                ('duree_essai_jours', models.PositiveSmallIntegerField()),
                ('actif', models.BooleanField()),
            ],
            options={
                'db_table': 'plans',
            },
        ),
    ]
