# Generated by Django 6.0.7 on 2026-07-16 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raison_sociale', models.CharField(max_length=150)),
                ('logo_url', models.URLField(blank=True, max_length=255, null=True)),
                ('couleur_principale', models.CharField(blank=True, max_length=7, null=True)),
                ('devise', models.CharField(max_length=3)),
                ('langue', models.CharField(max_length=5)),
                ('fuseau_horaire', models.CharField(max_length=50)),
                ('statut_abonnement', models.CharField(max_length=8)),
                ('date_debut_essai', models.DateField(blank=True, null=True)),
                ('date_fin_essai', models.DateField(blank=True, null=True)),
                ('email_contact', models.EmailField(max_length=150)),
                ('telephone_contact', models.CharField(blank=True, max_length=30, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entreprises', to='plan.plan')),
            ],
            options={
                'db_table': 'entreprises',
            },
        ),
    ]
