# Generated by Django 5.0.14 on 2026-07-21 16:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprises', '0004_entreprise_image_uploads'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprise',
            name='taux_commission_laveur',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
