# Generated by Django 5.0.14 on 2026-07-24 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprises', '0006_entreprise_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprise',
            name='date_debut_abonnement',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='date_fin_abonnement',
            field=models.DateField(blank=True, null=True),
        ),
    ]
