# Generated by Django 6.0.7 on 2026-07-16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("entreprises", "0002_alter_entreprise_plan"),
    ]

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=40)),
                ("libelle", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "entreprise",
                    models.ForeignKey(
                        blank=True,
                        db_column="entreprise_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roles",
                        to="entreprises.entreprise",
                    ),
                ),
            ],
            options={
                "db_table": "roles",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("entreprise", "code"),
                        name="uq_role_par_entreprise",
                    ),
                ],
            },
        ),
    ]
