# Generated by Django 6.0.7 on 2026-07-16 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entreprises', '0002_alter_entreprise_plan'),
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=150)),
                ('password', models.CharField(max_length=255)),
                ('statut', models.CharField(max_length=7)),
                ('entreprise', models.ForeignKey(db_column='entreprise_id', on_delete=django.db.models.deletion.PROTECT, related_name='utilisateurs', to='entreprises.entreprise')),
                ('invite_par', models.ForeignKey(blank=True, db_column='invite_par_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utilisateurs_invites', to='authentication.user')),
                ('role', models.ForeignKey(db_column='role_id', on_delete=django.db.models.deletion.PROTECT, related_name='utilisateurs', to='roles.role')),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
